# Generated by Django 3.0.8 on 2020-08-04 14:02

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=50, size=None)),
                ('published_date', models.DateField()),
                ('categories', django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=50, size=None)),
                ('average_rating', models.IntegerField(default=None)),
                ('ratings_count', models.IntegerField(default=None)),
                ('thumbnail', models.URLField()),
            ],
            options={
                'ordering': ['published_date'],
            },
        ),
    ]
