# Generated by Django 3.0.8 on 2020-08-05 11:50

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=550, size=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=550, size=10),
        ),
    ]
