# Generated by Django 3.0.8 on 2020-08-06 13:20

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_auto_20200805_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), default=None, max_length=550, size=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
