# Generated by Django 3.0.8 on 2020-08-09 13:37

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0007_auto_20200808_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), default=None, max_length=550, null=True, size=10),
        ),
    ]
