# Generated by Django 3.0.8 on 2020-08-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0008_auto_20200809_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(default=None, null=True),
        ),
    ]
