# Generated by Django 3.0.8 on 2020-08-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0009_auto_20200809_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['year']},
        ),
    ]
